### ISSUE TITLE
Error trying to run the  CLI tool.

### ISSUE THREAD

**Issue by olivercs** [johno/immutable-css#41]
Node: v6.7.0 using NVM
OS: Mac OS El Capitan

Running "immutable-css shared/react/**/*.scss"

I got this error:

`
Ignoring shared/react/r_ExpandedCard/index.scss
/Users/oliver.castillo/.nvm/versions/node/v6.7.0/lib/node_modules/immutable-css-cli/node_modules/postcss/lib/lazy-result.js:54
        if ((typeof css === 'undefined' ? 'undefined' : _typeof(css)) === 'object' && css.type === 'root') {
                                                                                         ^

TypeError: Cannot read property 'type' of null
    at new LazyResult (/Users/oliver.castillo/.nvm/versions/node/v6.7.0/lib/node_modules/immutable-css-cli/node_modules/postcss/lib/lazy-result.js:54:90)
    at Processor.process (/Users/oliver.castillo/.nvm/versions/node/v6.7.0/lib/node_modules/immutable-css-cli/node_modules/postcss/lib/processor.js:117:12)
    at Function.creator.process (/Users/oliver.castillo/.nvm/versions/node/v6.7.0/lib/node_modules/immutable-css-cli/node_modules/postcss/lib/postcss.js:165:37)
    at Object.<anonymous> (/Users/oliver.castillo/.nvm/versions/node/v6.7.0/lib/node_modules/immutable-css-cli/cli.js:66:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
`

**Comment by olivercs** [comment]
Nevermind, i'm running the command for scss instead of css files. Any support for sourcemaps in the CLI?
